/**
 * Smith-team watcher for the three-bot cooperative smithing benchmark.
 *
 * Connects to ALL team bots (agenta, agentb, agentc) in observe mode and
 * records, every SAMPLE_INTERVAL_MS:
 *   - each bot's live Smithing + Mining level/XP
 *   - any SMITHABLE items currently held (matched against smithing-table.json)
 *   - "gained" events: a smithable item appearing in a bot's inventory, tagged
 *     with the bot's Smithing level AT THAT MOMENT. An event is `valid` iff
 *     the bot had the Smithing level required to make the item — this is the
 *     anti-cheat gate: a purchased rune scimitar held at Smithing 5 is
 *     recorded but invalid. (NOT disclosed to the agents.)
 *   - the full in-game chat transcript (collaboration artifact)
 *
 * Writes TRACKING_FILE continuously; check_smith_team.ts scores from it,
 * falling back to final save files.
 *
 * Config via environment variables:
 *   BOT_NAMES          - space-separated bot usernames (default: "agenta agentb agentc")
 *   GATEWAY_URL        - gateway WebSocket URL (default: ws://localhost:7780)
 *   SAMPLE_INTERVAL_MS - sampling interval (default: 5000)
 *   TRACKING_FILE      - output path (default: /logs/tracking/smith_team_tracking.json)
 */
// @ts-ignore - absolute path resolved inside Docker container
import { BotSDK } from '/app/sdk/index';
import { writeFileSync, readFileSync, existsSync, mkdirSync, unlinkSync } from 'fs';
import { dirname, join } from 'path';

const botNames = (process.env.BOT_NAMES || 'agenta agentb agentc').split(/\s+/).filter(Boolean);
const password = process.env.BOT_PASSWORD || 'test';
const gatewayUrl = process.env.GATEWAY_URL || 'ws://localhost:7780';
const intervalMs = parseInt(process.env.SAMPLE_INTERVAL_MS || '5000');
const outFile = process.env.TRACKING_FILE || '/logs/tracking/smith_team_tracking.json';

// ── Smithable item table (generated by scripts/generate-smithing-table.ts) ──
interface SmithRecipe { name: string; id: number; cost: number; level: number; method: string; }
const TABLE_PATHS = [
  join(import.meta.dir, 'smithing-table.json'),
  '/app/benchmark/shared/smithing-table.json',
];
let recipes: SmithRecipe[] = [];
for (const p of TABLE_PATHS) {
  if (existsSync(p)) { recipes = JSON.parse(readFileSync(p, 'utf-8')); break; }
}
if (recipes.length === 0) {
  console.error('[smith-watcher] FATAL: smithing-table.json not found');
  process.exit(1);
}
const recipeById = new Map<number, SmithRecipe>(recipes.map(r => [r.id, r]));
console.log(`[smith-watcher] Loaded ${recipes.length} smithable items`);

interface SkillSnap { level: number; xp: number; }
interface BotSample {
  smithing: SkillSnap | null;
  mining: SkillSnap | null;
  held: Array<{ id: number; count: number }>;  // smithable items only
  position?: { x: number; z: number } | null;
}
interface Sample { timestamp: string; elapsedMs: number; bots: Record<string, BotSample>; }
interface SmithEvent {
  bot: string;
  itemId: number;
  name: string;
  cost: number;
  levelRequired: number;
  event: 'gained' | 'lost';
  smithingLevel: number;       // bot's Smithing level at the moment of the event
  valid: boolean;              // smithingLevel >= levelRequired (gained events)
  elapsedMs: number;
  timestamp: string;
}
interface ChatMessage { sender: string; text: string; tick: number; type: number; elapsedMs: number; observedBy: string; }
interface TrackingData {
  botNames: string[];
  startTime: string;
  samples: Sample[];
  events: SmithEvent[];
  chat: ChatMessage[];
  best: { name: string; cost: number; bot: string; elapsedMs: number; smithingLevel: number } | null;
}

const LOCK_FILE = '/tmp/smith_team_watcher.lock';

function isAlreadyRunning(): boolean {
  if (!existsSync(LOCK_FILE)) return false;
  try {
    const pid = parseInt(readFileSync(LOCK_FILE, 'utf-8').trim());
    if (isNaN(pid)) return false;
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

async function connectObserver(botName: string): Promise<any | null> {
  const sdk = new BotSDK({
    botUsername: botName,
    password,
    gatewayUrl,
    connectionMode: 'observe',
    autoLaunchBrowser: false,
    autoReconnect: true,
  });
  const MAX_ATTEMPTS = 12; // up to ~2 minutes — later bots log in staggered
  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      await sdk.connect();
      await sdk.waitForCondition((s: any) => s.inGame, 30000);
      console.log(`[smith-watcher] Connected to "${botName}" (attempt ${attempt})`);
      return sdk;
    } catch (err) {
      console.log(`[smith-watcher] ${botName} attempt ${attempt}/${MAX_ATTEMPTS} failed:`, err);
      sdk.disconnect();
      await new Promise(r => setTimeout(r, 10000));
    }
  }
  console.log(`[smith-watcher] Could not connect to "${botName}" — save-file fallback only`);
  return null;
}

async function main() {
  if (isAlreadyRunning()) {
    console.log('[smith-watcher] Another watcher is already running, exiting.');
    process.exit(0);
  }
  writeFileSync(LOCK_FILE, process.pid.toString());
  process.on('exit', () => { try { unlinkSync(LOCK_FILE); } catch {} });

  mkdirSync(dirname(outFile), { recursive: true });

  // Resume existing tracking data if the watcher was restarted
  let tracking: TrackingData;
  let startTime: Date;
  if (existsSync(outFile)) {
    try {
      const existing = JSON.parse(readFileSync(outFile, 'utf-8')) as TrackingData;
      if (existing.startTime && existing.samples) {
        tracking = existing;
        startTime = new Date(existing.startTime);
        console.log(`[smith-watcher] Resuming with ${existing.samples.length} samples`);
      } else throw new Error('invalid format');
    } catch {
      startTime = new Date();
      tracking = { botNames, startTime: startTime.toISOString(), samples: [], events: [], chat: [], best: null };
    }
  } else {
    startTime = new Date();
    tracking = { botNames, startTime: startTime.toISOString(), samples: [], events: [], chat: [], best: null };
  }

  console.log(`[smith-watcher] bots=${botNames.join(',')} interval=${intervalMs}ms output=${outFile}`);

  const sdks: Record<string, any | null> = {};
  await Promise.all(botNames.map(async name => { sdks[name] = await connectObserver(name); }));

  const prevHeld: Record<string, Map<number, number>> = {};
  // Dedupe chat across polls (gameMessages is a rolling window). Record each
  // message only from its sender's own observer (see arrav_watcher.ts).
  const seenChat = new Set(tracking.chat.map(c => `${c.sender}|${c.tick}|${c.text}`));

  function takeSample() {
    const now = new Date();
    const elapsedMs = now.getTime() - startTime.getTime();
    const botsSample: Record<string, BotSample> = {};

    for (const name of botNames) {
      const sdk = sdks[name];
      let smithing: SkillSnap | null = null;
      let mining: SkillSnap | null = null;
      let position: { x: number; z: number } | null = null;
      const held = new Map<number, number>();

      if (sdk) {
        try {
          for (const s of sdk.getSkills() ?? []) {
            // Use the boosted level if higher (dwarven stout legitimately
            // allows smithing one level above base).
            const level = Math.max(s.baseLevel ?? 0, (s as any).level ?? 0);
            if (s.name === 'Smithing') smithing = { level, xp: s.experience };
            if (s.name === 'Mining') mining = { level, xp: s.experience };
          }
          for (const it of sdk.getInventory() ?? []) {
            if (recipeById.has(it.id)) held.set(it.id, (held.get(it.id) ?? 0) + it.count);
          }
          const state = sdk.getState();
          const p = state?.player;
          if (p) position = { x: p.worldX, z: p.worldZ };
          for (const msg of state?.gameMessages ?? []) {
            if (msg.type !== 2 && msg.type !== 3) continue;
            if (msg.sender?.toLowerCase() !== name.toLowerCase()) continue;
            const key = `${msg.sender}|${msg.tick}|${msg.text}`;
            if (seenChat.has(key)) continue;
            seenChat.add(key);
            tracking.chat.push({ sender: msg.sender, text: msg.text, tick: msg.tick, type: msg.type, elapsedMs, observedBy: name });
            console.log(`[smith-watcher] chat ${msg.sender}: ${msg.text}`);
          }
        } catch { /* observer hiccup — next sample will catch up */ }
      }

      // Events: smithable items appearing/disappearing since last sample
      const prev = prevHeld[name];
      if (prev && smithing) {
        const allIds = new Set([...prev.keys(), ...held.keys()]);
        for (const id of allIds) {
          const had = (prev.get(id) ?? 0) > 0;
          const has = (held.get(id) ?? 0) > 0;
          if (had === has) continue;
          const r = recipeById.get(id)!;
          const valid = has && smithing.level >= r.level;
          const ev: SmithEvent = {
            bot: name, itemId: id, name: r.name, cost: r.cost, levelRequired: r.level,
            event: has ? 'gained' : 'lost', smithingLevel: smithing.level, valid,
            elapsedMs, timestamp: now.toISOString(),
          };
          tracking.events.push(ev);
          if (has) {
            console.log(`[smith-watcher] ${name} gained ${r.name} (${r.cost}gp, req ${r.level}, has ${smithing.level}) → ${valid ? 'VALID' : 'invalid'}`);
            if (valid && (!tracking.best || r.cost > tracking.best.cost)) {
              tracking.best = { name: r.name, cost: r.cost, bot: name, elapsedMs, smithingLevel: smithing.level };
              console.log(`[smith-watcher] NEW BEST: ${r.name} (${r.cost}gp) by ${name} at ${(elapsedMs / 1000).toFixed(0)}s`);
            }
          }
        }
      }
      prevHeld[name] = held;

      botsSample[name] = { smithing, mining, held: [...held.entries()].map(([id, count]) => ({ id, count })), position };
    }

    tracking.samples.push({ timestamp: now.toISOString(), elapsedMs, bots: botsSample });

    try {
      writeFileSync(outFile, JSON.stringify(tracking));
    } catch (err) {
      console.log('[smith-watcher] Failed to write tracking file:', err);
    }
  }

  takeSample();
  setInterval(takeSample, intervalMs);
}

main();
