#!/usr/bin/env bun
/**
 * Guard: the score normalization (raw XP -> real-game XP/min) is duplicated across
 * several files because each is copied STANDALONE into a container and therefore
 * cannot share an import:
 *   - shared/check_xp_rate.ts        -> /app/benchmark/shared/ in the image (agent-facing CLI)
 *   - shared/check_skill_xp.ts       -> /tests/ per task (THE scorer; writes reward.txt)
 *   - extractors/extract-skill-results.ts (leaderboard data)
 *   - views/shared-constants.js, app/components/TrajectoryModal.js (site display)
 *
 * If these drift, the CLI the agent optimizes against, the reward it is scored on,
 * and the number on the site silently disagree. This fails loudly instead.
 *
 * Usage: bun scripts/check-xp-normalization-sync.ts
 */
import { readFileSync } from 'fs';
import { join } from 'path';

const ROOT = join(import.meta.dir, '..');

const GAME_SPEED = 8;
const XP_MULTIPLIER = 25;

// Each site must divide by GAME_SPEED then XP_MULTIPLIER. Matches both the inline
// literal form (`/ 8 / 25`) and check_xp_rate.ts's named-constant form.
const SITES = [
  'shared/check_xp_rate.ts',
  'shared/check_skill_xp.ts',
  'extractors/extract-skill-results.ts',
  'views/shared-constants.js',
  'app/components/TrajectoryModal.js',
];

const LITERAL = new RegExp(`60000\\s*/\\s*${GAME_SPEED}\\s*/\\s*${XP_MULTIPLIER}\\b`);
const NAMED = /NORMALIZATION_DIVISOR|GAME_SPEED\s*\*\s*XP_MULTIPLIER/;

let failed = false;
for (const site of SITES) {
  let src: string;
  try {
    src = readFileSync(join(ROOT, site), 'utf-8');
  } catch {
    console.error(`FAIL ${site} — file not found (was it moved? update SITES)`);
    failed = true;
    continue;
  }
  if (LITERAL.test(src) || NAMED.test(src)) {
    console.log(`ok   ${site}`);
  } else {
    console.error(
      `FAIL ${site} — no ÷${GAME_SPEED}/÷${XP_MULTIPLIER} normalization found. ` +
      `If the divisor changed, change it in ALL of: ${SITES.join(', ')}`,
    );
    failed = true;
  }
}

// The docker/ copy is regenerated by docker/build.sh (cp ../shared/*.ts). If it has
// drifted from shared/, the next image ships stale agent-facing output.
const sharedCli = readFileSync(join(ROOT, 'shared/check_xp_rate.ts'), 'utf-8');
let dockerCli = '';
try {
  dockerCli = readFileSync(join(ROOT, 'docker/check_xp_rate.ts'), 'utf-8');
} catch {
  dockerCli = '';
}
if (dockerCli && dockerCli !== sharedCli) {
  console.error(
    'FAIL docker/check_xp_rate.ts differs from shared/check_xp_rate.ts — ' +
    'run `cp shared/check_xp_rate.ts docker/check_xp_rate.ts` (build.sh does this at build time, ' +
    'but the checked-in copy should not be stale).',
  );
  failed = true;
} else if (dockerCli) {
  console.log('ok   docker/check_xp_rate.ts in sync with shared/');
}

if (failed) {
  console.error('\nxp normalization is out of sync.');
  process.exit(1);
}
console.log(`\nall ${SITES.length + 1} sites agree: raw XP ÷ ${GAME_SPEED * XP_MULTIPLIER} = score.`);
